const data = [
  {
    id: 1,
    type: 1,
    name: 'Paneer Tikka',
    description: 'Description',
    price: 100,
    status: 'VEG',
  },
  {
    id: 2,
    type: 1,
    name: 'Aloo Tikki',
    description: 'Description',
    price: 80,
    status: 'VEG',
  },
  {
    id: 3,
    type: 1,
    name: 'Cheese Balls',
    description: 'Description',
    price: 150,
    status: 'VEG',
  },
  {
    id: 4,
    type: 2,
    name: 'BPM',
    description: 'Description',
    price: 100,
    status: 'VEG',
  },
  {
    id: 5,
    type: 2,
    name: 'Naan',
    description: 'Description',
    price: 80,
    status: 'VEG',
  },
  {
    id: 6,
    type: 2,
    name: 'Daal Fry',
    description: 'Description',
    price: 150,
    status: 'VEG',
  },
  {
    id: 7,
    type: 3,
    name: 'Mint Oreo Cake',
    description: 'Description',
    price: 100,
    status: 'VEG',
  },
  {
    id: 8,
    type: 3,
    name: 'Coconut Cream Cake',
    description: 'Description',
    price: 80,
    status: 'VEG',
  },
  {
    id: 9,
    type: 3,
    name: 'Brownies',
    description: 'Description',
    price: 150,
    status: 'NVEG',
  },
  {
    id: 10,
    type: 4,
    name: 'Sprite',
    description: 'Description',
    price: 100,
    status: 'VEG',
  },
  {
    id: 11,
    type: 4,
    name: 'Pepsi',
    description: 'Description',
    price: 80,
    status: 'VEG',
  },
  {
    id: 12,
    type: 4,
    name: '7 Up',
    description: 'Description',
    price: 150,
    status: 'VEG',
  },
  {
    id: 13,
    type: 4,
    name: 'Fanta',
    description: 'Description',
    price: 80,
    status: 'VEG',
  },
];

export {data};
